print("OI CLARA, ESSE É O MEU PRIMEIRO PROJETO NO RSTUDIO")

print("NÃO TENHO NADA EM MENTE PRA FALAR AGORA")

print("ENTÃO SÓ PRA FALAR QUE ESSE PRIMEIRO PROJETO É EM SUA HOMENAGEM ")

print("E QUE ESTOU COM SAUDADES")


print("E QUE VOU VOLTAR A JOGAR POKEMON POR SUA INFLUÊNCIA")